//Even Fibonacci numbers
//Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

fn main() {

    let mut current:u32 = 2;
    let mut previous:u32 = 1;
    let mut buffer:u32;
    let mut sum:u32 = 2;

    while current < 4000000{

        buffer = current;
        current = current + previous;

        if current % 2 == 0 {
            sum += current;
        }

        previous = buffer;
    }

    println!("Sum of all even fabionacci terms below 4000000 : {}",sum);
}